#!/bin/bash

export DESKTOP_CORE_NAME="clashx"
export DESKTOP_CORE_BIN_NAME="$DESKTOP_CORE_NAME"
export DESKTOP_CORE_VERSION=v1.118.0
export DESKTOP_CORE_ORG="yichengchen"

export DESKTOP_CORE_RELEASE_DOWNLOAD="https://github.com/${DESKTOP_CORE_ORG}/clashx/releases/download"
